categories:
  - title: ğŸš€ Features and Improvements
    labels:
      - feature
      - enhancement
      - performance
      - refactor
  - title: ğŸŒˆ Chore and Updates
    labels:
      - documentation
      - chore
      - test
      - ci
  - title: ğŸ› Bug Fixes
    labels:
      - bugfix
      - fix
  - title: ğŸ§° Breaking Changes
    label: breaking
version-resolver:
  major:
    labels:
      - breaking
  minor:
    labels:
      - enhancement
      - feature
      - performance
      - refactor
  patch:
    labels:
      - bugfix
      - documentation
      - fix
      - chore
      - test
      - ci
  default: patch
tag-template: $RESOLVED_VERSION
name-template: v$RESOLVED_VERSION
change-template: '* $TITLE (#$NUMBER)'
change-title-escapes: ''
exclude-labels:
  - skip-changelog
template: |
  ## Whatâ€™s Changed

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
