version: '2.0'

services:
  web:
      build: .
      ports:
      - "3000:3000"
      volumes:
        - ./:/usr/local/app/
        # the volume above prevents our host system's node_modules to be mounted
        - exclude:/usr/local/app/node_modules/

  storybook:
      build: .
      ports:
      - "3009:3003"
      volumes:
        - ./:/usr/local/app/
        # the volume above prevents our host system's node_modules to be mounted
        - exclude:/usr/local/app/node_modules/
      command: npm run storybook

volumes:
  exclude:
